### ISSUE TITLE
Select data for benchmarking

### ISSUE THREAD

**Issue by Anmol-Srivastava** [mitre/menelaus#151]
### Task

Select 1+ datasets that can be used as test / example data for NLP-based drift detection methods

### Impact

Helps test other tools / any algorithms developed within `menelaus`

**Comment by anmol-srivastava-mitre** [comment]
- [x] incorporate `wilds` datasets as optional dependency
- [x] attribute appropriately per license
- [x] add test harness
