### ISSUE TITLE
Improve Documentation of NLP Example

### ISSUE THREAD

**Issue by Anmol-Srivastava** [mitre/menelaus#164]
### Task
- [x] correct / fill in docstrings for added components
- [x] add top-level docstrings 
- [x] fill out prose for example notebook
