### ISSUE TITLE
Release experimental NLP code

### ISSUE THREAD

**Issue by Anmol-Srivastava** [mitre/menelaus#166]
### Task
Migrate `experimental` into `menelaus` proper. 
- [ ] assure testing/formatting is finished
- [ ] rename to `nlp` for now -- we may merge detector, alarm, and transform classes later
- [ ] assure documentation adjusts correctly
- [ ] dependencies from `experimental` option must now be in main `install_requires`
