### ISSUE TITLE
Address indiscriminate drift alarm in NN-DVI

### ISSUE THREAD

**Issue by anmol-srivastava-mitre** [mitre/menelaus#36]
### Task
When currently applied to 'realistic' and sizable data, the NNDVI implementation alarms drift constantly and irrespective of the user-selected k (for k-NN) and number of sampling times for drift-threshold estimation. Until this is fixed, NNDVI is bugged and unusable. 

**_Note:_** the referenced dataset is a private dataset of ~180K data points, split into ~9 batches. A MRE of such data is needed for testing and development in this issue.

### Impact
This will debug and un-block an otherwise completed drift detector and partitioner, and hence expand the zoo of detectors provided by `menelaus`. 

### Details
At minimum:

- [x] reproduce a dataset which causes the above behavior
- [ ] debug `NNSpacePartitioner.build()`, `NNSpacePartitioner.compute_nnps_distance()` for any partitioner-side problems
- [ ] debug `NNDVI.update()` and `NNDVI.compute_drift_threshold()` for any detector-side problems

**Comment by Anmol-Srivastava** [comment]
Just did a simple merge of `dev` into `bugfix/...` -- I think more remains to be done, tentatively

- let's just use `BatchDetector` as the base
- make sure `NNDVI` works with validation changes made since
- make sure docs/examples build? 
- etc.
